### ISSUE TITLE
Wikipedia pages don't load on Mountain Lion

### ISSUE THREAD

**Issue by sbliven** [wikiwidget/wikipedia-widget#4]
After upgrading to Mountain Lion the widget has stopped working. After searching for a page the status icon spins forever and the page never loads.

I've tried reinstalling. Anyone else seeing this?

**Comment by sbliven** [comment]
Hmm, after stepping through with the debugger it seems to be a problem with the DOMParser.  My Element objects don't have innerHTML properties, oddly. I'm not sure if this is a change to the DOMParser API in mountain lion, or if it's a more general problem. Can anyone confirm whether the widget works/doesn't work on 10.7 and 10.8?

**Comment by sbliven** [comment]
This is fixed by patch #5

**Comment by sbillig** [comment]
I no longer have a Mac at home, so I can't help out with this.  The best I can do is confirm that it is indeed NOT working on my 10.7.4 work computer.  Same behavior you're seeing, and this log message: 

10/24/12 3:02:19.052 PM DashboardClient: (com.whatsinthehouse.widget.wikipedia) undefined: TypeError: 'undefined' is not an object (line: 0)

Speaking of not having a mac... any interest in taking over maintenance on this thing?  I'm obviously not doing the best job.

**Comment by sbillig** [comment]
Just tested your fix, and it's working on 10.7.  Nice work yet again.

**Comment by sbliven** [comment]
I use this widget almost daily, so I'll definitely keep fixing things that break and pushing patches to you. If you were thinking of something beyond that, shoot me an email and we'll discuss it. spencer.bliven at gmail
